{
 "title": "EstacionMetereologicaCompleto",
 "tags": [
  "WeatherStation",
  "Dashboard"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Humedad Actual (%)",
   "type": "gauge",
   "description": "Porcentaje de humedad actual",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT humidity FROM etws WHERE time_index >= NOW() - '20 min'::INTERVAL ORDER BY time_index DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Historial de Humedad (%)",
   "type": "timeseries",
   "description": "Porcentaje de humedad de las útimas 24 horas",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT humidity, time_index FROM etws WHERE time_index >= NOW() - '24 hours'::INTERVAL"
    }
   ]
  },
  {
   "title": "Humedad Máxima (%)",
   "type": "stat",
   "description": "Humedad máxima registrada en las últimas 8 horas",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(humidity) FROM etws WHERE time_index >= NOW() - '8 hours'::INTERVAL"
    }
   ]
  },
  {
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT wind_dir FROM etws WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Humedad Mínima(%)",
   "type": "stat",
   "description": "Humedad Mínima registrada en las últimas 8 horas",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(humidity) FROM etws WHERE time_index >= NOW() - '8 hours'::INTERVAL"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Radiación Solar (W/m²)",
   "type": "gauge",
   "description": "Radiación Solar actual",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT solar_radiation FROM etws WHERE time_index >= NOW() - '20 min'::INTERVAL ORDER BY time_index DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Historial Radiación Solar",
   "type": "timeseries",
   "description": "Radiación Solar reportada en las últimas 8 horas",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    {
     "rawSql": "SELECT solar_radiation, time_index FROM etws WHERE time_index >= NOW() - '1 day'::INTERVAL"
    }
   ]
  },
  {
   "title": "PM2.5 Mínimo (μg/m³)",
   "type": "stat",
   "description": "Calidad del aire: PM2.5 mínimo registrado en las últimas 8 Horas",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(PM_2_5) FROM etws WHERE time_index >= NOW() - '8 hours'::INTERVAL"
    }
   ]
  },
  {
   "title": "Velocidad Viento (m/s)",
   "type": "gauge",
   "description": "Velocidad del viento actual",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT wind_speed FROM etws WHERE time_index >= NOW() - '20 min'::INTERVAL ORDER BY time_index DESC LIMIT 1 "
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "PM 2.5 (μg/m³)",
   "type": "gauge",
   "description": "Calidad del aire: PM2.5 Actual registrado",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pm_2_5 FROM etws WHERE time_index >= NOW() - '20 min'::INTERVAL ORDER BY time_index DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Historial Calidad del aire PM 2.5 / PM 1.0 (μg/m³)",
   "type": "timeseries",
   "description": "Calidad del aire PM2.5 en las últimas 24 Horas",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT pm_2_5, pm_10, time_index FROM etws WHERE time_index >= NOW() - '1 day'::INTERVAL LIMIT 50 "
    }
   ]
  },
  {
   "title": "PM 2.5 Máximo (μg/m³)",
   "type": "stat",
   "description": "Calidad del aire: PM2.5 Máximo registrado en las últimas 8 Horas",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(PM_2_5) FROM etws WHERE time_index >= NOW() - '8 hours'::INTERVAL"
    }
   ]
  },
  {
   "title": "PM 1.0 (μg/m³)",
   "type": "gauge",
   "description": "Calidad del aire: PM1.0 Actual registrado",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pm_10 FROM etws WHERE time_index >= NOW() - '20 min'::INTERVAL ORDER BY time_index DESC LIMIT 1 "
    }
   ]
  }
 ]
}