{
 "title": "Sensores estación meteorológica",
 "description": "Mediante ésta agrupación de dashboards podemos visualizar en tiempo real cada 30 segundos los datos arrojados por los registros de los sensores de la estación meteorológica.",
 "time": { "from": "2024-04-24T13:11:00.609Z", "to": "2024-04-24T14:14:14.739Z" },
 "panels": [
  {
   "title": "Temperatura valor",
   "type": "stat",
   "description": "Mediante éste dashboard podemos visualizar los datos arrojados sobre la temperatura de la estación meteorológica medida en grados Fahrenheit con su valor.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperature, entity_id, time_index FROM etws LIMIT 50 "
    }
   ]
  },
  {
   "title": "Humedad valor",
   "type": "stat",
   "description": "Mediante éste dashboard podemos ver en tiempo real los datos arrojados por el sensor de humedad de la estación meteorológica medida en una escala de 0 a 100% con su valor actual.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT humidity, entity_id, time_index FROM etws LIMIT 50 "
    }
   ]
  },
  {
   "title": "Presión valor",
   "type": "stat",
   "description": "Mediante éste dashboard podemos visualizar a tiempo real la presión atmosférica medida en pulgadas de mercurio con su valor actual.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pressure, entity_id, time_index FROM etws LIMIT 50 "
    }
   ]
  },
  {
   "title": "Dirección del aire valor",
   "type": "stat",
   "description": "Con éste dashboard podemos ver la dirección del aire medida en grados arrojada por la estación meteorológica con su valor exacto.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT wind_dir, entity_id, time_index FROM etws LIMIT 50 "
    }
   ]
  },
  {
   "title": "Radiación solar",
   "type": "stat",
   "description": "Mediante éste dashboard podemos visualizar en tiempo real la radiación solar arrojada por la estación meteorológica medida en vatios por metros al cuadrado.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT solar_radiation, entity_id, time_index FROM etws LIMIT 50 "
    }
   ]
  },
  {
   "title": "Velocidad del aire valor",
   "type": "stat",
   "description": "Mediante ésta tabla podemos visualizar la velocidad del aire medida en metros por hora con su valor real.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT wind_speed, entity_id, time_index FROM etws LIMIT 50 "
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "description": "Mediante éste dashboard podemos visualizar los datos arrojados sobre la temperatura de la estación meteorológica medida en grados Fahrenheit.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT temperature, entity_id, time_index FROM etws LIMIT 50 "
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "timeseries",
   "description": "Mediante éste dashboard podemos ver en tiempo real los datos arrojados por el sensor de humedad de la estación meteorológica medida en una escala de 0 a 100%.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT humidity, entity_id, time_index FROM etws LIMIT 50 "
    }
   ]
  },
  {
   "title": "Presión",
   "type": "timeseries",
   "description": "Mediante éste dashboard podemos visualizar a tiempo real la presión atmosférica medida en pulgadas de mercurio.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT pressure, entity_id, time_index FROM etws LIMIT 50 "
    }
   ]
  },
  {
   "title": "Dirección del aire",
   "type": "timeseries",
   "description": "Con éste dashboard podemos ver la dirección del aire medida en grados arrojada por la estación meteorológica.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT wind_dir, entity_id, time_index FROM etws LIMIT 50 "
    }
   ]
  },
  {
   "title": "Velocidad del aire",
   "type": "timeseries",
   "description": "Mediante ésta tabla podemos visualizar la velocidad del aire medida en metros por hora.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT wind_speed, entity_id, time_index FROM etws LIMIT 50 "
    }
   ]
  },
  {
   "title": "Radiación solar",
   "type": "timeseries",
   "description": "Mediante éste dashboard podemos visualizar en tiempo real la radiación solar arrojada por la estación meteorológica medida en vatios por metros al cuadrado.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT solar_radiation, entity_id, time_index FROM etws LIMIT 50 "
    }
   ]
  }
 ]
}