{
 "title": "SmartMeters1",
 "description": "Parte 1 del dashboard correspondiente",
 "tags": [
  "SmartMeters",
  "Dashboard"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energía activa exportada  (Wh)",
   "type": "stat",
   "description": "Energía activa exportada ",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT activeenergyexport FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Energía activa exportada día  (Wh)",
   "type": "stat",
   "description": "Energía activa exportada ",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(activeenergyexport) FROM etsmartmeter WHERE time_index >= NOW() - '24 hours'::INTERVAL"
    }
   ]
  },
  {
   "title": "Energía activa importada (Wh)",
   "type": "stat",
   "description": "Energía activa exportada ",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT activeenergyimport FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  { "title": "Alertas de Baja Frecuencia", "type": "alertlist", "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 } },
  { "title": "Alertas de Alta Frecuencia", "type": "alertlist", "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 } },
  {
   "title": "Frecuencia (Hz)",
   "type": "gauge",
   "description": "Frecuencia",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT frecuency FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Energía activa importada día  (Wh)",
   "type": "stat",
   "description": "Energía activa exportada ",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(activeenergyimport) FROM etsmartmeter WHERE time_index >= NOW() - '24 hours'::INTERVAL"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Armónico Corriente Fase 1",
   "type": "gauge",
   "description": "Armónicos de corriente de la fase 1\n\n",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT harmonicsi1 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Armónico Corriente Fase2",
   "type": "gauge",
   "description": "Armónicos de corriente de la fase 2\n",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT harmonicsi2 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Armónico Corriente Fase 3",
   "type": "gauge",
   "description": "Armónicos de corriente de la fase 3\n",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT harmonicsi3 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Historial de Armónicos Fase 1, 2 y 3",
   "type": "timeseries",
   "description": "Historial de Armónicos Fase 1, 2 y 3 en las últimas 24 horas",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT harmonicsi1, harmonicsi2, harmonicsi3, time_index FROM etsmartmeter WHERE time_index >= NOW() - '1 day'::INTERVAL"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Armónico Tensión Fase 1",
   "type": "gauge",
   "description": "Armónicos de tensión de la fase 1\n\n",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT harmonicsv1 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Armónico Tensión Fase 2",
   "type": "gauge",
   "description": "Armónicos de tensión de la fase 2\n\n",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT harmonicsv2 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Armónico Tensión Fase 3",
   "type": "gauge",
   "description": "Armónicos de tensión de la fase 3\n\n",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT harmonicsv3 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Armonicos De Tensión De La Fase 1, 2 y 3",
   "type": "timeseries",
   "description": "Armonicos De Tensión De La Fase 1, 2 y 3 en las últimas 24 horas",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT harmonicsv1, harmonicsv2, harmonicsv3, time_index FROM etsmartmeter WHERE time_index >= NOW() - '1 day'::INTERVAL"
    }
   ]
  }
 ]
}