{
 "title": "SmartMeters2",
 "description": "Parte 1 del dashboard correspondiente",
 "tags": [
  "SmartMeters",
  "Dashboard"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "bargauge",
   "description": "Magnitud de corriente fase 1 ",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT i1 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index DESC"
    }
   ]
  },
  {
   "title": "Magnitud y ángulo de corriente fase 1  ",
   "type": "briangann-gauge-panel",
   "description": "Magnitud y ángulo de corriente fase 1  ",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT i1angle FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index LIMIT 1"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "Magnitud de corriente fase 1 ",
   "gridPos": { "h": 7, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT i2 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Magnitud y ángulo de corriente fase 2",
   "type": "briangann-gauge-panel",
   "description": "Magnitud y ángulo de corriente fase 2",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT i2angle FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index LIMIT 1"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "Magnitud de corriente fase 1 ",
   "gridPos": { "h": 7, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT i1 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Magnitud y ángulo de corriente fase 3",
   "type": "briangann-gauge-panel",
   "description": "Magnitud y ángulo de corriente fase 3",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT i3angle FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Magnitud Neutro",
   "type": "gauge",
   "description": "Magnitud Corriente Neutro\n\n",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"in\" FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index LIMIT 1 "
    }
   ]
  },
  {
   "title": "Factor de potencia de Fase 1",
   "type": "gauge",
   "description": "Factor de potencia de Fase 1\n",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT powerfactor1 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index LIMIT 1"
    }
   ]
  },
  {
   "title": "Factor de potencia de Fase 2",
   "type": "gauge",
   "description": "Factor de potencia de Fase 2\n",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT powerfactor2 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index LIMIT 1"
    }
   ]
  },
  {
   "title": "Factor de potencia de Fase 3",
   "type": "gauge",
   "description": "Factor de potencia de Fase 3\n",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT powerfactor3 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index LIMIT 1"
    }
   ]
  },
  {
   "title": "Factor de potencia de Fase 1, 2 y 3",
   "type": "timeseries",
   "description": "Historial de Armónicos Fase 1, 2 y 3 en las últimas 24 horas",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT powerfactor1, powerfactor2, powerfactor3, time_index FROM etsmartmeter WHERE time_index >= NOW() - '1 day'::INTERVAL"
    }
   ]
  },
  {
   "title": "h Energía reaactiva exportada",
   "type": "stat",
   "description": "h Energía reaactiva exportada",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT reactiveenergyexport FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "h Energía reactiva exportada día",
   "type": "stat",
   "description": "h Energía reactiva exportada día",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(reactiveenergyexportday) FROM etsmartmeter WHERE time_index >= NOW() - '24 hours'::INTERVAL"
    }
   ]
  },
  {
   "title": "h Energía reactiva importada",
   "type": "stat",
   "description": "h Energía reaactiva exportada",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT reactiveenergyimport FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Factor de potencia de Fase 1",
   "type": "gauge",
   "description": "Factor de potencia de Fase 1\n",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT activepower FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Potencia Activa 1, 2 y 3",
   "type": "timeseries",
   "description": "Historial de Armónicos Fase 1, 2 y 3 en las últimas 24 horas",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT activepower1, activepower2, activepower3, time_index FROM etsmartmeter WHERE time_index >= NOW() - '1 day'::INTERVAL"
    }
   ]
  },
  {
   "title": "h Energía reactiva importada día  ",
   "type": "stat",
   "description": "h Energía reactiva exportada día",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(reactiveenergyexportday) FROM etsmartmeter WHERE time_index >= NOW() - '24 hours'::INTERVAL"
    }
   ]
  }
 ]
}