{
 "title": "SmartMeters3",
 "description": "Parte 3 del dashboard correspondiente",
 "tags": [
  "SmartMeters",
  "Dashboard"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Tensión fase 1",
   "type": "gauge",
   "description": "Tensión fase 1\n",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT v1 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Ángulo tensión fase 1",
   "type": "briangann-gauge-panel",
   "description": "Ángulo tensión fase 1",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT v1angle FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Tensión fase 2",
   "type": "gauge",
   "description": "Tensión fase 2",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT v2 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Ángulo tensión fase 2",
   "type": "briangann-gauge-panel",
   "description": "Ángulo tensión fase 2",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT v2angle FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Tensión fase 3",
   "type": "gauge",
   "description": "Tensión fase 3\n",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT v3 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Ángulo tensión fase 3",
   "type": "briangann-gauge-panel",
   "description": "Ángulo tensión fase 3",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT v3angle FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Fase 1 por unidad   ",
   "type": "bargauge",
   "description": "Fase 1 por unidad   ",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT v1_ps FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Fase 2 por unidad   ",
   "type": "bargauge",
   "description": "Fase 2 por unidad   ",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT v2_ps FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Fase 3 por unidad   ",
   "type": "bargauge",
   "description": "Fase 3 por unidad   ",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT v3_ps FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index DESC LIMIT 1"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Potencia reactiva (w)",
   "type": "stat",
   "description": "Potencia reactiva (w)",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT reactivepower FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "P. reactiva fase 1",
   "type": "stat",
   "description": "Potencia reactiva fase 1",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT reactivepower1 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Distorsión armónica de corriente",
   "type": "gauge",
   "description": "Distorsión total armónica de corriente\n",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT relativethdcurrent FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Distorsión armónica de tensión  ",
   "type": "gauge",
   "description": "Distorsión total armónica de tensión  \n\n",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT relativethdvoltage FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "Distorsión armónica de potencia  ",
   "type": "gauge",
   "description": "Distorsión total armónica de potencia  \n\n",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT relativethdpower FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index"
    }
   ]
  },
  {
   "title": "P. reactiva fase 2",
   "type": "stat",
   "description": "Potencia reactiva fase 2",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT reactivepower2 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Factor de potencia total",
   "type": "timeseries",
   "description": "Historial de Factor de potencia total en las últimas 24 horas",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT totalpowerfactor, time_index FROM etsmartmeter WHERE time_index >= NOW() - '1 day'::INTERVAL"
    }
   ]
  },
  {
   "title": "P. reactiva fase 3",
   "type": "stat",
   "description": "Potencia reactiva fase 3",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT reactivepower3 FROM etsmartmeter WHERE time_index >= NOW() - '5 min'::INTERVAL ORDER BY time_index DESC LIMIT 1"
    }
   ]
  }
 ]
}